<a href="https://colab.research.google.com/github/Mohamed-Willy/ML-Course/blob/PYTHON/ML_1_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Mounting Drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# **Loading Data**

In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Importing the dataset
dataset = pd.read_csv('/content/drive/MyDrive/ML A-Z/Part 1 - Data Preprocessing/Data Preprocessing/Python/Data.csv')
X = dataset.iloc[:, :-1].values # Take all columns except the last one for x
Y = dataset.iloc[:, -1].values # Take last column for y
print(X)
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# **Missing Data**

In [ ]:
# Importing the libraries
from sklearn.impute import SimpleImputer
'''
  strategy:
    mean
    median
    most_frequent
'''
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')

In [ ]:
# Fiting the model
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# **Data Encoding**

In [ ]:
# Importing the libraries
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_encoder_X = LabelEncoder()
'''
  reminder:
    passthrough -> leaves the non encoded columns
    drop -> removes non selected columns
    transformers:
      list of tuples -> (name, transformer, columns)
'''
one_hot_encoder_X = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

In [ ]:
# Appling LabelEncoder model (Not best due to appling value)
X[:, 0] = label_encoder_X.fit_transform(X[:, 0])
print(X)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 61000.0]
 [0 35.0 58000.0]
 [2 38.0 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [ ]:
# Appling OneHotEncoder model
X = np.array(one_hot_encoder_X.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
# Appling on Y
label_encoder_Y = LabelEncoder()
Y = label_encoder_Y.fit_transform(Y)
print(Y)

[0 1 0 0 1 1 0 1 0 1]


# **Train Test Split**

In [ ]:
#Importing libraries
from sklearn.model_selection import train_test_split

In [ ]:
# Appling model
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)
print("X train:")
print(X_train)
print("X test:")
print(X_test)
print("Y train:")
print(y_train)
print("Y test:")
print(y_test)

X train:
[[0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 48.0 79000.0]]
X test:
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
Y train:
[0 1 0 1 1 0 0 1]
Y test:
[0 1]


# **Feature scaling**

In [ ]:
# Importing Libraries
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [ ]:
# Appling Model (Scaling them to a certain range)
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])
print("X train:")
print(X_train)
print("X test:")
print(X_test)

X train:
[[0.0 0.0 1.0 -0.28942984211696865 -0.2767210428728637]
 [0.0 1.0 0.0 -8.326672684688674e-17 -0.2767210428728637]
 [0.0 0.0 1.0 -0.28942984211696865 -1.0430254692900245]
 [1.0 0.0 0.0 -0.7235746052924217 -0.5321558516785839]
 [0.0 0.0 1.0 -1.8812939737602963 -1.3836052143643183]
 [0.0 1.0 0.0 1.4471492105848434 1.5964675550357517]
 [1.0 0.0 0.0 0.5788596842339373 0.6598732560814441]
 [1.0 0.0 0.0 1.1577193684678746 1.255887809961458]]
X test:
[[0.0 1.0 0.0 -1.4471492105848434 -0.8727355967528776]
 [1.0 0.0 0.0 -0.43414476317545303 0.23414857473857686]]
