<a href="https://colab.research.google.com/github/Mohamed-Willy/ML-Course/blob/PYTHON/ML_3_MultipleLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Multiple Linear Regression**
<hr><br>
Similar to simple Linear Regression problem but with multiple independent variables<br><br>
Y = b<sub>1</sub>X<sub>1</sub> + b<sub>2</sub>X<sub>2</sub> + ......... + b<sub>n</sub>X<sub>n</sub> + C

# **Building Model Methods**
<hr><br>
1- All-in<br>
2- Backward Elimination<br>
3- Forward Selection<br>
4- Bidirectional Elimination<br>
5- Score Comparison (brute force)


# **Dummy Variables**
<hr><br>
when you have a categorical variable<br>
we include all except one to avoid dummy variable trap<br>
there is one for each category in the categorical varible column

# **Mounting Drive**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# **Preparing Dataset**

In [2]:
# Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Loading dataset
dataset = pd.read_csv('/content/drive/MyDrive/ML A-Z/Part 2 - Regression/Section 5 - Multiple Linear Regression/Python/50_Startups.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values
# print(dataset)
print(X)
# print(Y)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [4]:
# Encoding categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)
# Avoiding the Dummy variable trap
X = X[:, 1:]
# print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [5]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)
print("X train:")
print(X_train)
print("X test:")
print(X_test)
print("Y train:")
print(Y_train)
print("Y test:")
print(Y_test)

X train:
[[1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 63408.86 129219.61 46085.25]
 [0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 75328.87 144135.98 134050.07]
 [0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 44069.95 51283.14 197029.42]
 [0.0 0.0 28754.33 118546.05 172795.67]
 [0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 0.0 64664.71 139553.16 137962.62]
 [0.0 0.0 46426.07 157693.92 210797.67]
 [1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 0.0 0.0 116983.8 45173.06]
 [0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 1.0 61136.38 152701.92 88218.23]
 [0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 78389.47 153773.43 299737.29]
 [1.0 0.0 130298.13 145530.06 323876.68]
 [1.0 0.0 1315.46 115816.21 297114.46]
 [0.0 1.0 46014.02 85047.44 205517.64]
 [1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 73994.56 122782.75 303319.26]
 [0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 0.0 38558.51 82982.09 174999.3]
 [0.0

# **Fitting MLR Model**

In [6]:
# Importing Library
from sklearn.linear_model import LinearRegression

In [7]:
# Fitting Model
regressor = LinearRegression()
regressor.fit(X_train, Y_train)
print(X_train)
print(Y_train)

[[1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 63408.86 129219.61 46085.25]
 [0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 75328.87 144135.98 134050.07]
 [0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 44069.95 51283.14 197029.42]
 [0.0 0.0 28754.33 118546.05 172795.67]
 [0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 0.0 64664.71 139553.16 137962.62]
 [0.0 0.0 46426.07 157693.92 210797.67]
 [1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 0.0 0.0 116983.8 45173.06]
 [0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 1.0 61136.38 152701.92 88218.23]
 [0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 78389.47 153773.43 299737.29]
 [1.0 0.0 130298.13 145530.06 323876.68]
 [1.0 0.0 1315.46 115816.21 297114.46]
 [0.0 1.0 46014.02 85047.44 205517.64]
 [1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 73994.56 122782.75 303319.26]
 [0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 0.0 38558.51 82982.09 174999.3]
 [0.0 1.0 6560

# **Testing Model**

In [8]:
# Predicting the Test set results
Y_pred = regressor.predict(X_test)
# Setting decimals to only two digits
np.set_printoptions(precision=2)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[ 43802.49  42559.73]
 [150846.74 152211.77]
 [ 98697.95  96778.92]
 [114983.52 108552.04]
 [ 61294.92  65200.33]
 [ 46258.83  64926.08]
 [ 58841.7   69758.98]
 [ 52046.46  35673.41]
 [165639.12 156991.12]
 [115984.4  126992.93]]


# **Backward Elimination**

In [9]:
# Importing Library
import statsmodels.api as sm
# import statsmodels.formula as sm

In [10]:
X = np.append(arr= np.ones((50, 1)).astype(int), values= X, axis= 1)

In [11]:
# Choose highest P>|t| value and remove is until the max value is smaller than 0.05
X_opt = np.array(X[:, [0, 1, 2, 3, 4, 5]], dtype= float)
regressor_OLS = sm.OLS(endog=Y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sun, 24 Sep 2023   Prob (F-statistic):           1.34e-27
Time:                        14:12:01   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""